target: list of dependencies
<a literal tab>commmand to build target from dependencies

knights_tour: knights_tour.c
	gcc knights_tour.c -o knights_tour

clean:
	rm knights_tour



#for java exec
#hello.class: hello.java
#	javac hello.java